### ISSUE TITLE
Broken in mechanic 2

### ISSUE THREAD

**Issue by typoman** [asaumierdemers/AddOverlap#5]
I get this error if I install from mechanic 2 but not from the robodocs fork:
```
********************
Installing 'Add Overlap' report:
  Traceback (most recent call last):
      File "AddOverlap.py", line 3, in <module>
    ModuleNotFoundError: No module named 'ufoLib'
    
During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "AddOverlap.py", line 5, in <module>
    ModuleNotFoundError: No module named 'robofab'
  
********************
```
Maybe updating the mechanic 2 link would fix this?

**Comment by colinmford** [comment]
#3 would fix this
